### ISSUE TITLE
Holograms sometimes does not disappear on 1.7.X

### ISSUE THREAD

**Issue by piter909** [ProtocolSupport/ProtocolSupportLegacyHologram#2]
Holograms sometimes do not disappear on 1.7.X.
I have plugin that adds timed holographic chat messages above players head. Sometimes messages do not disappear on 1.7.X version, players have to disconnect and reconnect to clear their holograms seeing.
It can be caused by lags, but I am not sure.

**Comment by Shevchik** [comment]
Cased by this line of code
https://github.com/ProtocolSupport/ProtocolSupportLegacyHologram/blob/master/src/protocolsupportlegacyhologram/HologramHandler.java#L122
If first entity id of the destroy entity packet is not an armorstand, other entity ids are not handled at all.

**Comment by piter909** [comment]
Thanks for reply.
Is there any way to fix this problem?

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by piter909** [comment]
It works perfectly now! :) Thanks!
