### ISSUE TITLE
Using this source with 4.22.1 and Paperspigot 1.8.8?

### ISSUE THREAD

**Issue by mattyokan** [ProtocolSupport/ProtocolSupportLegacyHologram#3]
Hi @Shevchik ,

Just wondering what sort of modifications I would have to make in order for this plugin to be functional with ProtocolSupport build 4.22.1 on my Paperspigot 1.8.8. I know you have said that it's not designed for this build and I also know that you don't fix bugs with older versions of ProtocolSupport, but I am asking for help because of how I have a server that has to target 1.7-1.12 with Spigot 1.8.8 at its base, and as such I am required to use 4.22.1 to have support for 1.7 players. I would greatly appreciate if you would provide any help with this as I would absolutely love to have support for Holograms on 1.7.

Thank you.

**Comment by Shevchik** [comment]
No help for outdated versions.
